# **PyTorch Fundamentals**

## **Imports**

In [1]:
# Import pytorch
import torch

# Check pytorch version
torch.__version__

'2.0.1+cu118'

In [2]:
# Imports
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

## **Creating a Tensor**

### **Scaler**

In [3]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
# Dimension of scaler
scaler.ndim

0

In [5]:
# Get tensor back as Python int
scaler.item()

7

### **Vector**

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# Dimension of vector
vector.ndim

1

In [8]:
# Shape of vector
vector.shape

torch.Size([2])

### **MATRIX**

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# Dimension of MATRIX
MATRIX.ndim

2

In [11]:
# Shape of MATRIX
MATRIX.shape

torch.Size([2, 2])

In [12]:
# MATRIX indexing
MATRIX[0]

tensor([7, 8])

### **TENSOR**

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
# Dimension of TENSOR
TENSOR.ndim

3

In [15]:
# Shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
# TENSOR indexing
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
# TENSOR indexing
TENSOR[0][1]

tensor([3, 6, 9])

## **Random Tensors**

In [18]:
# Create a random tensor of size (3, 4)
random_2d_tensor = torch.rand((3, 4))
print(random_2d_tensor)
print(random_2d_tensor.ndim)
print(random_2d_tensor.shape)
print(random_2d_tensor.size())

tensor([[0.3349, 0.6246, 0.6041, 0.3420],
        [0.2641, 0.2846, 0.1527, 0.3150],
        [0.5836, 0.4303, 0.8291, 0.5698]])
2
torch.Size([3, 4])
torch.Size([3, 4])


In [19]:
# Create a random tensor of size (2, 3, 2)
random_3d_tensor = torch.rand((2, 3, 2))
print(random_3d_tensor)
print(random_3d_tensor.ndim)
print(random_3d_tensor.shape)
print(random_3d_tensor.size())

tensor([[[0.4678, 0.9294],
         [0.3201, 0.2329],
         [0.7093, 0.3782]],

        [[0.0097, 0.9829],
         [0.2622, 0.1856],
         [0.7512, 0.7379]]])
3
torch.Size([2, 3, 2])
torch.Size([2, 3, 2])


In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand((224, 224, 3)) # (Height, Width, Color Channels)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand((3, 224, 224)) # (Color Channels, Height, Width)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## **Zeros and Ones**

In [22]:
# Create a tensor of all zeros
zero_2d_tensor = torch.zeros((2, 4))
zero_2d_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all zeros
zero_3d_tensor = torch.zeros((2, 3, 2))
zero_3d_tensor

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [24]:
# Create a tensor of all ones
one_2d_tensor = torch.ones((2, 4))
one_2d_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
# Create a tensor of all ones
one_3d_tensor = torch.ones((2, 3, 2))
one_3d_tensor

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [26]:
# Check data type
print(zero_2d_tensor.dtype)
print(zero_3d_tensor.dtype)
print(one_2d_tensor.dtype)
print(one_3d_tensor.dtype)

torch.float32
torch.float32
torch.float32
torch.float32


In [27]:
# Check data type
print(type(zero_2d_tensor))
print(type(zero_3d_tensor))
print(type(one_2d_tensor))
print(type(one_3d_tensor))

<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>


## **Range of Tensors and Tensors-Like**

In [28]:
# Use .arange() to generate a tensor
range_tensor = torch.arange(1, 11)
range_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Use .arange() to generate a tensor with step
range_step_tensor = torch.arange(0, 1000, 77)
range_step_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [30]:
# Creating tensors like -> Creates a tensor of same shape as of the input tensor
zeros_tensor_like = torch.zeros_like(range_tensor)
zeros_tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
# Random tensor
random_3d_tensor = torch.rand((2, 3, 3))
print(random_3d_tensor)

# Generate a tensor like
random_3d_tensor_like = torch.zeros_like(random_3d_tensor)
random_3d_tensor_like

tensor([[[0.5121, 0.6486, 0.3660],
         [0.8971, 0.5641, 0.1398],
         [0.0432, 0.8332, 0.7854]],

        [[0.2069, 0.6606, 0.7137],
         [0.0973, 0.3581, 0.0797],
         [0.6470, 0.1519, 0.6373]]])


tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

## **Tensor DataTypes**

**Note:** Tensor datatypes can lead to 3 big errors when used incorrectly with PyTorch:
1. Tensors not having same datatype
2. Tensors not having same shape / size
3. Tensors not on same devices (`cpu / cuda`)

### **Float 32 tensor**
`Default DataType -> float32`

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([[2.0, 4.0, 6.0],
                                [3.0, 6.0, 9.0]],
                               dtype = None, # What data type is the tensor (e.g. float16, float32 and float64)
                               device = None, # What device is your tensor on
                               requires_grad = False) # Wheter or not to track gradients with tensor operations
print(float_32_tensor)

# Check datatype
print(float_32_tensor.dtype)

tensor([[2., 4., 6.],
        [3., 6., 9.]])
torch.float32


### **Float 16 tensor**

In [33]:
# Convert the float_32_tensor to float16 dtype
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor)

# Check datatype
print(float_16_tensor.dtype)

tensor([[2., 4., 6.],
        [3., 6., 9.]], dtype=torch.float16)
torch.float16


### **Trying Basic Operations**

**Trying to operate on different datatype tensors to check for possible errors.**

In [34]:
# Try multiplying float16 and float32 tensors
float_16_tensor * float_32_tensor

tensor([[ 4., 16., 36.],
        [ 9., 36., 81.]])

In [35]:
# Initialize a int32 tensor
int_32_tensor = torch.tensor([[2, 4, 6],
                              [3, 6, 9]], dtype = torch.int32)

# Try multiplying int32 and float32 tensor
int_32_tensor * float_32_tensor

tensor([[ 4., 16., 36.],
        [ 9., 36., 81.]])

## **Getting Tensor Attributes**
1. Get datatype -  `tensor.dtype`
2. Get shape - `tensor.shape`
3. Get the device - `tensor.device`

In [36]:
# Create a random tensor
random_tensor = torch.rand((3, 4))
random_tensor

tensor([[0.2409, 0.8742, 0.9298, 0.4593],
        [0.1092, 0.1479, 0.3546, 0.1368],
        [0.5492, 0.8240, 0.7177, 0.8658]])

In [37]:
# Check datatype of the tensor
print(random_tensor)
print(f"\nDataType of tensor\t: {random_tensor.dtype}")
print(f"\nShape of tensor\t\t: {random_tensor.shape}")
print(f"\nSize of tensor\t\t: {random_tensor.size()}")
print(f"\nTensor is on\t\t: {random_tensor.device}")

tensor([[0.2409, 0.8742, 0.9298, 0.4593],
        [0.1092, 0.1479, 0.3546, 0.1368],
        [0.5492, 0.8240, 0.7177, 0.8658]])

DataType of tensor	: torch.float32

Shape of tensor		: torch.Size([3, 4])

Size of tensor		: torch.Size([3, 4])

Tensor is on		: cpu


## **Mathematical Tensor Operations**
Tensor operatiosn include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division

In [38]:
# Create a tensor
torch_2d_tensor = torch.tensor([[2, 4, 6],
                          [3, 6, 9]])
torch_2d_tensor

tensor([[2, 4, 6],
        [3, 6, 9]])

In [39]:
# Add 10 to the tensor
torch_2d_tensor + 10

tensor([[12, 14, 16],
        [13, 16, 19]])

In [40]:
# Subtract 10 from the tensor
torch_2d_tensor - 10

tensor([[-8, -6, -4],
        [-7, -4, -1]])

In [41]:
# Multiply 10 to the tensor
torch_2d_tensor * 10

tensor([[20, 40, 60],
        [30, 60, 90]])

In [42]:
# Divide tensor by 10
torch_2d_tensor / 10

tensor([[0.2000, 0.4000, 0.6000],
        [0.3000, 0.6000, 0.9000]])

## **Matrix Multiplication**
Two main ways of performing multiplication in neural networds and deep learning:
1. Element-wise multiplication
2. Matrix multiplication

### **Element-wise Multiplication**

In [43]:
# Initialize tensors
tensor_a = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])
print(tensor_a)

tensor_b = torch.tensor([[4, 5, 6],
                         [7, 8, 9]])
print(tensor_b)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[4, 5, 6],
        [7, 8, 9]])


In [44]:
# Scaler multiplication
print(tensor_a * 10)
print(tensor_b * 10)

tensor([[10, 20, 30],
        [40, 50, 60]])
tensor([[40, 50, 60],
        [70, 80, 90]])


In [45]:
# Multiply tensor_a and tensor_b element wise
tensor_a * tensor_b

tensor([[ 4, 10, 18],
        [28, 40, 54]])

### **Matrix Multiplication**
There are 2 main rules for matrix multiplication:
1. The `inner dimensions` must match:
    * `(3, 2) @ (3, 2)` wont work.
    * `(3, 2) @ (2, 3)` will work.
    * `(2, 3) @ (3, 2)` will work.
2. The resulting matrix has the shape of the `outer dimensions`:
    * `(3, 2) @ (2, 3) -> (3, 3)`
    * `(2, 3) @ (3, 2) -> (2, 2)`

In [46]:
# Initialize 1D tensors
tensor_a = torch.tensor([1, 2, 3])
print(tensor_a)

tensor_b = torch.tensor([4, 5, 6])
print(tensor_b)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [47]:
# Get the dot product
torch.matmul(tensor_a, tensor_b)

tensor(32)

In [48]:
# Initialize 2D tensors
tensor_a = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])
print(tensor_a, tensor_a.shape)

tensor_b = torch.tensor([[4, 5],
                         [6, 7],
                         [8, 9]])
print(tensor_b, tensor_b.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[4, 5],
        [6, 7],
        [8, 9]]) torch.Size([3, 2])


In [49]:
# Get the dot product
torch.matmul(tensor_a, tensor_b)

tensor([[ 40,  46],
        [ 94, 109]])

In [50]:
# Get the dot product
# @ symbol -> Dot product
tensor_a @ tensor_b

tensor([[ 40,  46],
        [ 94, 109]])

#### **Dealing with Shape Errors**

In [51]:
# Initializing 2D tensors (matrices)
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
print(tensor_a, tensor_a.shape)

tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
print(tensor_b, tensor_b.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]]) torch.Size([3, 2])
tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]) torch.Size([3, 2])


In [52]:
# Fix tensor shape issue
# Take transpose of one of the tensor
tensor_b = tensor_b.T
print(tensor_b, tensor_b.shape)

tensor([[ 7,  8,  9],
        [10, 11, 12]]) torch.Size([2, 3])


In [53]:
# Now get the dot product the tensors
%%time
tensor_a @ tensor_b

CPU times: user 35 µs, sys: 6 µs, total: 41 µs
Wall time: 45.8 µs


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [54]:
# Now get the dot product the tensors
%%time
torch.matmul(tensor_a, tensor_b)

CPU times: user 0 ns, sys: 38 µs, total: 38 µs
Wall time: 42 µs


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [55]:
# Now get the dot product the tensors
%%time
torch.mm(tensor_a, tensor_b)

CPU times: user 62 µs, sys: 11 µs, total: 73 µs
Wall time: 79.6 µs


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## **Tensor Aggregation**

In [56]:
# Initialize a tensor
tensor = torch.arange(0, 100, 10)
tensor, tensor.shape, tensor.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 torch.Size([10]),
 torch.int64)

In [57]:
# Find the min
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [58]:
# Find the max
torch.max(tensor), tensor.max()

(tensor(90), tensor(90))

In [59]:
# Find the mean
# NOTE: torch.arange() generate the tensor of datatype int64 / Long
# NOTE: Make sure to convert tensor into floating point for calculation of mean
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [60]:
# Find the sum
torch.sum(tensor), tensor.sum()

(tensor(450), tensor(450))

## **Positional Min and Max**

In [61]:
# View the tensor
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
# Find the index of smallest element
torch.argmin(tensor), tensor.argmin()

(tensor(0), tensor(0))

In [63]:
# Find the index of largest element
torch.argmax(tensor), tensor.argmax()

(tensor(9), tensor(9))

In [64]:
# Get the minimum value using the argmin()
tensor[torch.argmin(tensor)], tensor[tensor.argmin()]

(tensor(0), tensor(0))

In [65]:
# Get the largest value using the argmax()
tensor[torch.argmax(tensor)], tensor[tensor.argmax()]

(tensor(90), tensor(90))

## **Tensor Operations**

* Reshaping - reshapes an input tensor into a defined shape.
* Viewing - Return a view of an input tensor of certail shape but keep the same memory.
* Stacking - Combine multiple tensors on top of each other (vstack / dim = 0) and side-by-side (hstack / dim = 1).
* Sqeezing - Removes all `1` dimensions from a tensor.
* Unsqeezing - Add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [66]:
# Initialize a tensor using arange of datatype float32
tensor = torch.arange(1, 11, dtype = torch.float32)
tensor, tensor.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

### **Reshaping**

In [67]:
# Reshaping the tensor
tensor_reshaped = tensor.reshape((10)) # Flattens the tensor into 1D
print(tensor_reshaped, tensor_reshaped.shape)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])


In [68]:
# Reshaping the tensor
tensor_reshaped = tensor.reshape((1, 10)) # Row tensor
print(tensor_reshaped, tensor_reshaped.shape)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])


In [69]:
# Reshaping the tensor
tensor_reshaped = tensor.reshape((10, 1)) # Column tensor
print(tensor_reshaped, tensor_reshaped.shape)

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]]) torch.Size([10, 1])


In [70]:
# Reshaping the tensor
tensor_reshaped = tensor.reshape((5, 2))
print(tensor_reshaped, tensor_reshaped.shape)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) torch.Size([5, 2])


In [71]:
# Reshaping the tensor
tensor_reshaped = tensor.reshape((2, 5))
print(tensor_reshaped, tensor_reshaped.shape)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]]) torch.Size([2, 5])


### **Viewing**

In [72]:
# Change the view of tensor
view_tensor = tensor.view((10))
view_tensor

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [73]:
# Change the view of tensor
view_tensor = tensor.view((1, 10))
view_tensor

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [74]:
# Change the view of tensor
view_tensor = tensor.view((10, 1))
view_tensor

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [75]:
# Change the view of tensor
view_tensor = tensor.view((5, 2))
view_tensor

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [76]:
# Change the view of tensor
view_tensor = tensor.view((2, 5))
view_tensor

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

### **Updating View Tensor**

In [77]:
# Print view_tensor
print(view_tensor)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])


In [78]:
# Update view_tensor -> The respective elements will be updated
view_tensor[0][0] = 15

# Print the tensors
print(view_tensor)
print(tensor)

tensor([[15.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
tensor([15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [79]:
# Update view_tensor -> The respective elements will be updated
view_tensor[1][0] = 20

# Print the tensors
print(view_tensor)
print(tensor)

tensor([[15.,  2.,  3.,  4.,  5.],
        [20.,  7.,  8.,  9., 10.]])
tensor([15.,  2.,  3.,  4.,  5., 20.,  7.,  8.,  9., 10.])


### **Stacking**

In [80]:
# Print the tensor
tensor

tensor([15.,  2.,  3.,  4.,  5., 20.,  7.,  8.,  9., 10.])

In [81]:
# Stack the tensors vertically
vstack_tensor = torch.stack([tensor, tensor, tensor, tensor], dim = 0)
vstack_tensor

tensor([[15.,  2.,  3.,  4.,  5., 20.,  7.,  8.,  9., 10.],
        [15.,  2.,  3.,  4.,  5., 20.,  7.,  8.,  9., 10.],
        [15.,  2.,  3.,  4.,  5., 20.,  7.,  8.,  9., 10.],
        [15.,  2.,  3.,  4.,  5., 20.,  7.,  8.,  9., 10.]])

In [82]:
# Stack the tensors horizontally
hstack_tensor = torch.stack([tensor, tensor, tensor, tensor], dim = 1)
hstack_tensor

tensor([[15., 15., 15., 15.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [20., 20., 20., 20.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

### **Squeeze**

In [83]:
# Initialie a tensor containing 1D tensors
tensor = torch.rand((1, 3, 3))
tensor, tensor.shape

(tensor([[[0.3009, 0.9518, 0.2176],
          [0.4121, 0.4835, 0.4422],
          [0.6944, 0.6933, 0.3037]]]),
 torch.Size([1, 3, 3]))

In [84]:
# Squeeze the tensor
sqeezed_tensor = tensor.squeeze()
sqeezed_tensor, sqeezed_tensor.shape

(tensor([[0.3009, 0.9518, 0.2176],
         [0.4121, 0.4835, 0.4422],
         [0.6944, 0.6933, 0.3037]]),
 torch.Size([3, 3]))

### **Unsqueeze**

In [85]:
# Initialize a tensor
tensor = torch.tensor([1, 2, 3, 4, 5])
tensor, tensor.shape

(tensor([1, 2, 3, 4, 5]), torch.Size([5]))

In [86]:
# Unsquueze the tensor
unsqeezed_tensor = torch.unsqueeze(tensor, 0)
unsqeezed_tensor, unsqeezed_tensor.shape

(tensor([[1, 2, 3, 4, 5]]), torch.Size([1, 5]))

In [87]:
# Unsquueze the tensor
unsqeezed_tensor = torch.unsqueeze(tensor, 1)
unsqeezed_tensor, unsqeezed_tensor.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5]]),
 torch.Size([5, 1]))

### **Permute**

In [88]:
# Initialize a random tensor
tensor = torch.rand((224, 224, 3)) # [Height, Width, Colour Channels]
tensor.shape

torch.Size([224, 224, 3])

In [89]:
# Change the dimension
permuted_tensor = torch.permute(tensor, (2, 0, 1)) # [Colour Channels, Height, Width]
permuted_tensor.shape

torch.Size([3, 224, 224])

## **Indexing**

In [90]:
# Creating a tensor
tensor = torch.arange(1, 10).reshape((1, 3, 3))
tensor, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [91]:
# Get data from the tensor using index
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [92]:
# Get data from the tensor using index
tensor[0][0] # tensor[0, 0]

tensor([1, 2, 3])

In [93]:
# Get data from the tensor using index
tensor[0][0][0] # tensor[0, 0, 0]

tensor(1)

In [94]:
# Select multiple values using slicing
tensor[:, :, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [95]:
# Select multiple values using slicing
tensor[0, :, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [96]:
# Select multiple values using slicing
tensor[0, 1, :]

tensor([4, 5, 6])

In [97]:
# Select multiple values using slicing
tensor[0, :, 1]

tensor([2, 5, 8])

In [98]:
# Index on tensor to return 9
tensor[0][2][2]

tensor(9)

In [99]:
# Slice on tensor to return 3, 6, 9
tensor[0, :, 2]

tensor([3, 6, 9])

## **PyTorch Tensors & Numpy**

### **Numpy to PyTorch Tensor**
`torch.from_numpy(ndarray)`

In [100]:
# Initialize a numpy array for type float32
# NOTE: Default datatype of numpy is float64 / int64
# NOTE: PyTorch reflects array datatype unless specified
array = np.arange(1, 10, dtype = np.float32).reshape((3, 3))
array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [101]:
# Convert numpy array to tensor
tensor = torch.from_numpy(array)
tensor, tensor.dtype

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.float32)

In [102]:
# Update array
array += 1

# View the array and tensor
array, tensor

(array([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]], dtype=float32),
 tensor([[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]]))

**NOTE: Updating array `will update` the tensor if `torch.from_numpy()` method is used.**

In [103]:
# Initialize a numpy array for type float32
# NOTE: Default datatype of numpy is float64 / int64
# NOTE: PyTorch reflects array datatype unless specified
array = np.arange(1, 10, dtype = np.float32).reshape((3, 3))
array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [104]:
# Use the torch.tensor() method
tensor = torch.tensor(array)
tensor, tensor.dtype

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.float32)

In [105]:
# Update array
array += 1

# View the array and tensor
array, tensor

(array([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]], dtype=float32),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

**NOTE: Updating array `will not update` the tensor if `torch.tensor()` method is used.**

### **PyTorch Tensor to Numpy**
`torch.Tensor.numpy()`

In [106]:
# Create a tensor
tensor = torch.arange(1, 10).reshape((3, 3)).type(torch.float32)
tensor, tensor.dtype

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.float32)

In [107]:
# Convert the tensor to numpy array
array = tensor.numpy()
array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [108]:
# Update the tensor
tensor += 1

# View the tensor and array
tensor, array

(tensor([[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]]),
 array([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]], dtype=float32))

**NOTE: Updating tensor `will update` the array if `torch.Tensor.numpy()` method is used.**

In [109]:
# Create a tensor
tensor = torch.arange(1, 10).reshape((3, 3)).type(torch.float32)
tensor, tensor.dtype

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.float32)

In [110]:
# Convert the tensor to numpy array
array = np.asarray(tensor)
array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [111]:
# Update the tensor
tensor += 1

# View the tensor and array
tensor, array

(tensor([[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]]),
 array([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]], dtype=float32))

**NOTE: Updating tensor `will update` the array if `np.asarray()` method is used.**

In [112]:
# Create a tensor
tensor = torch.arange(1, 10).reshape((3, 3)).type(torch.float32)
tensor, tensor.dtype

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.float32)

In [113]:
# Convert the tensor to numpy array
array = np.array(tensor)
array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [114]:
# Update the tensor
tensor += 1

# View the tensor and array
tensor, array

(tensor([[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]]),
 array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=float32))

**NOTE: Updating tensor `will not update` the array if `np.array()` method is used.**

## **Reproduciblity**
**Taking the Random Out of Random**

In [115]:
# Create random tensors
random_tensor_a = torch.rand((3, 4))
random_tensor_b = torch.rand((3, 4))

In [116]:
# Print the tensors
random_tensor_a, random_tensor_b

(tensor([[0.9502, 0.4343, 0.3896, 0.5296],
         [0.3250, 0.8432, 0.6271, 0.3063],
         [0.8323, 0.0926, 0.9028, 0.9599]]),
 tensor([[0.2538, 0.7961, 0.5516, 0.2101],
         [0.1695, 0.8752, 0.4422, 0.4365],
         [0.3156, 0.5338, 0.8754, 0.3084]]))

In [117]:
# Check for same values
random_tensor_a == random_tensor_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

**`random_seed` for reproducible random numbers**

In [118]:
# Declare the value for random seed
RANDOM_SEED = 42

In [119]:
# Again create random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand((3, 4))

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand((3, 4))

In [120]:
# Print the tensors
random_tensor_c, random_tensor_d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [121]:
# Check for same values
random_tensor_c == random_tensor_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## **GPU in PyTorch**

In [122]:
# Check if GPU is available
!nvidia-smi

Sun Jul 16 06:27:10 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [123]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [124]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [125]:
# Count number of devices
torch.cuda.device_count()

1

## **Tensors (and Models) on GPU**

In [126]:
# Create a tensor (default on cpu)
tensor_on_cpu = torch.tensor([1, 2, 3])
tensor_on_cpu, tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [127]:
# Move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]], device='cuda:0'),
 device(type='cuda', index=0))

In [128]:
# Move tensor back to cpu
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu, tensor_on_cpu.device

(tensor([[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]]),
 device(type='cpu'))